name: python3.9env
channels:
  - conda-forge
dependencies:
  - alembic
  - badger-opt
  - bmad
  - bayesian-optimization
  - black
  - blosc
  - bokeh
  - botorch
  - caproto
  - cothread
  - cx_oracle
  - dask
  - dateparser
  - deap
  - dm-tree
  - epics-base
  - epicscorelibs
  - gpflow
  - gpy
  - greenlet
  - gym
  - h5py
  - hdf5
  - holoviews
  - impact-t
  - ipython
  - ipywidgets
  - jinja2
  - jupyter
  - jupyterlab
  - kafka-python
  - keras
  - lume-epics
  - lume-impact
  - lume-model
  - matplotlib
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - mkdocs-jupyter
  - mock
  - mpi
  - mpi4py
  - multiset
  - notebook
  - numexpr
  - numpy=1.23.5
  - openmpi
  - openpmd-beamphysics
  - pandas
  - panel
  - pcaspy
  - pip
  - pint
  - pydantic>=2.3
  - pydm
  - pyepics
  - pyqt
  - pyqtgraph
  - pyqtwebengine
  - pytao
  - pytest
  - pytest-qt
  - python=3.9
  - pytorch
  - pytz
  - pyzmq
  - qtpy
  - requests
  - scikit-learn
  - scikit-image
  - scipy
  - seaborn
  - six
  - sqlite
  - sqlalchemy
  - pytables
  - tensorflow
  - tensorflow-probability
  - theano
  - treelib
  - pip:
    - git+https://github.com/slaclab/edmbutton
    - git+https://github.com/slaclab/edlgenerator
    - git+https://github.com/slaclab/slacepics
    - git+https://github.com/slaclab/subprocessca
    - git+https://github.com/slaclab/edef
    - matlab-wrapper
    - git+https://github.com/slaclab/meme
    - git+https://github.com/slaclab/pyca
    - git+https://github.com/slaclab/lcls-live
    - git+https://github.com/slaclab/lcls-tools
    - git+https://github.com/slaclab/mps_database
    - git+https://github.com/slaclab/mps_history
    - git+https://github.com/ChristopherMayes/Xopt
    - git+https://github.com/dylanmkennedy/emitopt
    - jax>=0.4.16
    - jaxlib>=0.4.16
    - ipaddress
    - Cheetah3
    - p4p
    - opencv-contrib-python
#
# Stuff that isn't on PyPI or GitHub that is manually installed in prod
# epics-batch-get
# gauge-widget
# lcls-parameters
# logicgate
# matlog
# model
# physicselog
# wmctrl
