name: Publish RHEL7 compatible nightly release

on:
  schedule:
    - cron: '35 22 * * *'

jobs:
  build:
    env:
      ENVIRONMENT_NAME: python3.9env
      ENVIRONMENT_FILE_PATH: rhel7-environment.yml
      TEST_FILE: test.sh
    runs-on: ubuntu-latest
    name: Build environment
    steps:
      - name: Build environment
        uses: jbellister-slac/lcls-rhel6-conda-pack@6b0b0a01c4c67cc0275ea7bedf9e9d51ae54c9c1
      - name: Upload artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ENVIRONMENT_NAME }}.tar.gz
          tag: rhel7-nightly
          overwrite: true
          file_glob: true
