name: Publish RHEL7 compatible nightly release

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    env:
      ENVIRONMENT_NAME: python3.9env
      ENVIRONMENT_FILE_PATH: nightly-rhel7-environment.yml
      TEST_FILE: test.sh
    runs-on: ubuntu-latest
    name: Build environment
    steps:
      - name: Build environment
        uses: jbellister-slac/lcls-rhel7-conda-pack@b5283552ae868de41e9c5753386353e4301ad711
      - name: Upload artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ENVIRONMENT_NAME }}.tar.gz
          tag: rhel7-nightly
          overwrite: true
          file_glob: true
